enabledmessage: ""

disabledmessage: ""

messages_enabled: true

globalmessage_enabled: true

consolecommand_enabled: true

teleportspawn: true

#For all the commands use variable %player to get player's name

message: ""

globalmessage: ""

consolecommand: ""